baseURL       = "https://blog.rocksolid.work"
languageCode  = "zh-CN"
title         = "首页"
theme         = "roxo"
summarylength = 25
hasCJKLanguage = true

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
      [markup.goldmark.extensions.cjk]
        eastAsianLineBreaks = false
        eastAsianLineBreaksStyle = 'simple'
        enable = false
        escapedSpace = false
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.insert]
          enable = true
        [markup.goldmark.extensions.extras.mark]
          enable = true
        [markup.goldmark.extensions.extras.subscript]
          enable = true
        [markup.goldmark.extensions.extras.superscript]
          enable = true
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = []
          inline = []
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    # style = 'catppuccin-latte'
    style = 'emacs'
    # style = 'rose-pine-dawn'
    # style = 'manni'
    # style = 'solarized-light'
    tabWidth = 2
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

# Site Menus
[menu]
  [[menu.nav]]
    name    = "博客"
    url     = "blog"
    weight  = 1
  [[menu.nav]]
    name    = "分类"
    url     = "categories"
    weight  = 2
  [[menu.nav]]
    name    = "专栏"
    url     = "series"
    weight  = 3
  [[menu.nav]]
    name    = "标签"
    url     = "tags"
    weight  = 4
  [[menu.nav]]
    name    = "关于"
    url     = "about"
    weight  = 5
  [[menu.nav]]
    name    = "Buy me coffee"
    url     = "buy-me-coffee"
    weight  = 6

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'

[services]
  # Google Analitycs
  [services.googleAnalytics]
    ID = 'G-692VCFTQRM'

# Site Params
[params]
  logo = "images/logo-orange.png"
  favicon = "images/logo-square.png"
  name = "顽石@RockSolid"
  # Meta data
  description = "The RockSolid Work Blog"
  author = "RockSolid"

  # Site Consts
  [params.const]
    prev = "Prev"
    next = "Next"

  # Banner Section
  [params.banner]
    enable                = true
    title               = "致虚极 守静笃 万物并作 吾以观复"
    slogan               = "MAKE SOMETHINGS & HAVING FUN"

  # Copyright
  [params.copyright]
    # Copyright, left + datetime + right, 
    copyright_left = "Copyright © 2013-"
    copyright_right = " RockSolid. All Rights Reserved. 顽石信息科技 版权所有. 版权许可 "
    license = "<a href=\"https://creativecommons.org/licenses/by-nc-nd/3.0/cn/\" target=\"_blank\">CC BY-NC-ND 3.0 CN</a>"
    # ICP related
    icp = "陕ICP备15008230号-1"